name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/htmx-fastapi-app:latest
          ghcr.io/${{ github.repository_owner }}/htmx-fastapi-app:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      USE_KEYVAULT: true
      AZURE_KEYVAULT_URL: https://hemmelegfastapi.vault.azure.net/

    
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get Container App URL
      id: geturl
      run: |
        # Add error checking and verbose output
        echo "Retrieving Container App FQDN..."
        FQDN=$(az containerapp show --name htmx-fastapi-app --resource-group demohtmxrg --query "properties.configuration.ingress.fqdn" -o tsv)
    
        # Verify we got a value
        if [ -z "$FQDN" ]; then
          echo "Error: Could not retrieve FQDN for the Container App"
          exit 1
        fi
    
        echo "FQDN retrieved: $FQDN"
        echo "Setting callback URL..."
        CALLBACK_URL="https://$FQDN/auth/google/callback"
        echo "Callback URL: $CALLBACK_URL"
    
        # Set the output variable correctly
        echo "CALLBACK_URL=$CALLBACK_URL" >> $GITHUB_OUTPUT

    - name: Prepare environment variables
      run: |
        CALLBACK_URL="https://$FQDN/auth/google/callback"
        echo "Prepared environment variables:"
        echo "USE_KEYVAULT=true"
        echo "AZURE_KEYVAULT_URL=https://hemmelegfastapi.vault.azure.net/"
        echo "AZURE_CLIENT_ID=****" # Don't print the actual secret
        echo "GOOGLE_CALLBACK_URL=$CALLBACK_URL"
    
        # Create a single string for all environment variables
        ENV_VARS="USE_KEYVAULT=true AZURE_KEYVAULT_URL=https://hemmelegfastapi.vault.azure.net/ AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }} GOOGLE_CALLBACK_URL=$CALLBACK_URL"
        echo "ENV_VARS=$ENV_VARS" >> $GITHUB_ENV

    - name: Deploy with Azure CLI
      run: |
        az containerapp update \
          --name htmx-fastapi-app \
          --resource-group demohtmxrg \
          --image ghcr.io/${{ github.repository_owner }}/htmx-fastapi-app:${{ github.sha }} \
          --set-env-vars ${{ env.ENV_VARS }}