name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/htmx-fastapi-app:latest
          ghcr.io/${{ github.repository_owner }}/htmx-fastapi-app:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      USE_KEYVAULT: true
      AZURE_KEYVAULT_URL: https://hemmelegfastapi.vault.azure.net/

    
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get Container App URL
      id: geturl
      run: |
        FQDN=$(az containerapp show --name htmx-fastapi-app --resource-group demohtmxrg --query properties.configuration.ingress.fqdn -o tsv)
        echo "CALLBACK_URL=https://$FQDN/auth/google/callback" >> $GITHUB_OUTPUT
        
    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        resourceGroup: demohtmxrg
        containerAppName: htmx-fastapi-app
        imageToDeploy: ghcr.io/${{ github.repository_owner }}/htmx-fastapi-app:${{ github.sha }}
        environmentVariables: |
          USE_KEYVAULT=true
          AZURE_KEYVAULT_URL=https://hemmelegfastapi.vault.azure.net/
          AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
          GOOGLE_CALLBACK_URL=${{ steps.geturl.outputs.CALLBACK_URL }}
